insert into books (author, title, priceOld, price) values ('Drucie Goodbourn', 'exploit real-time e-commerce', '$203.23', '$43.37');
insert into books (author, title, priceOld, price) values ('Marcia Aggiss', 'utilize real-time interfaces', '$260.31', '');
insert into books (author, title, priceOld, price) values ('Giovanni Bigg', 'extend strategic e-services', '$272.00', '$151.04');
insert into books (author, title, priceOld, price) values ('Duffie Eynon', 'iterate integrated solutions', '$271.58', '');
insert into books (author, title, priceOld, price) values ('Anselma McKennan', 'cultivate magnetic e-commerce', '$278.43', '$54.44');
insert into books (author, title, priceOld, price) values ('Gert Kira', 'architect vertical ROI', '$282.54', '$102.61');
insert into books (author, title, priceOld, price) values ('Clerc Djakovic', 'disintermediate extensible architectures', '$295.38', '$181.27');
insert into books (author, title, priceOld, price) values ('Stacee Elsy', 'extend leading-edge methodologies', '$283.08', '$97.96');
insert into books (author, title, priceOld, price) values ('Dorotea Bonhill', 'integrate one-to-one systems', '$258.51', '$52.25');
insert into books (author, title, priceOld, price) values ('Minni Bunney', 'revolutionize 24/7 infrastructures', '$260.79', '$33.69');
insert into books (author, title, priceOld, price) values ('Berty Gandley', 'enhance innovative e-services', '$256.54', '$160.98');
insert into books (author, title, priceOld, price) values ('Raynard Tesdale', 'maximize 24/365 e-tailers', '$262.07', '$34.06');
insert into books (author, title, priceOld, price) values ('Joanna Hutfield', 'scale integrated architectures', '$257.66', '$32.97');
insert into books (author, title, priceOld, price) values ('Dannie Glidder', 'e-enable frictionless web services', '$288.19', '$90.52');
insert into books (author, title, priceOld, price) values ('Timmie Adshede', 'strategize B2B channels', '$232.27', '$44.83');
insert into books (author, title, priceOld, price) values ('Fernando Neads', 'syndicate compelling deliverables', '$287.45', '$101.89');
insert into books (author, title, priceOld, price) values ('Teddy Guilliland', 'utilize bleeding-edge users', '$281.37', '$146.21');
insert into books (author, title, priceOld, price) values ('Paloma Grebert', 'cultivate 24/365 networks', '$270.99', '$184.76');
insert into books (author, title, priceOld, price) values ('Kristos Usher', 'embrace plug-and-play platforms', '$278.36', '$77.71');
insert into books (author, title, priceOld, price) values ('Darcey Rohmer', 'target innovative paradigms', '$298.94', '$130.01');
insert into books (author, title, priceOld, price) values ('Cristie Isacsson', 'generate open-source e-business', '$276.57', '$113.25');
insert into books (author, title, priceOld, price) values ('Lindsay Coutthart', 'implement user-centric e-markets', '$254.70', '$115.31');
insert into books (author, title, priceOld, price) values ('Helyn Schneidar', 'utilize magnetic supply-chains', '$279.70', '$77.86');
insert into books (author, title, priceOld, price) values ('Bette-ann Askem', 'e-enable dot-com supply-chains', '$297.83', '$110.15');
insert into books (author, title, priceOld, price) values ('Dom Robuchon', 'facilitate efficient eyeballs', '$232.30', '$131.48');

-- insert into books (author, title, email, priceOld, price) values ('Frances Segoe', 'Re-contextualized intangible solution', 'fsegoe0@mayoclinic.com', 211, 0);
-- insert into books (author, title, email, priceOld, price) values ('Angelika Andresser', 'Synchronised zero administration leverage', 'aandresser1@biglobe.ne.jp', 241, 144);
-- insert into books (author, title, email, priceOld, price) values ('Emlyn Chalk', 'Profit-focused neutral model', 'echalk2@desdev.cn', 228, 0);
-- insert into books (author, title, email, priceOld, price) values ('Fritz Labbett', 'Distributed uniform interface', 'flabbett3@yale.edu', 485, 114);
-- insert into books (author, title, email, priceOld, price) values ('Merry Hateley', 'Horizontal fault-tolerant task-force', 'mhateley4@guardian.co.uk', 585, 0);
-- insert into books (author, title, email, priceOld, price) values ('Raleigh Frangleton', 'Enterprise-wide actuating project', 'rfrangleton5@ucsd.edu', 279, 120);
-- insert into books (author, title, email, priceOld, price) values ('Kylie O'' Liddy', 'Reactive attitude-oriented portal', 'ko6@merriam-webster.com', 500, 75);
-- insert into books (author, title, email, priceOld, price) values ('Sydney Haysey', 'Team-oriented demand-driven monitoring', 'shaysey7@360.cn', 241, 109);
-- insert into books (author, title, email, priceOld, price) values ('Giraud Oattes', 'Synergized executive orchestration', 'goattes8@yahoo.co.jp', 585, 99);
-- insert into books (author, title, email, priceOld, price) values ('Rebeca Sergison', 'Expanded global challenge', 'rsergison9@intel.com', 405, 147);
-- insert into books (author, title, email, priceOld, price) values ('Angus Salvati', 'Right-sized 4th generation service-desk', 'asalvatia@facebook.com', 460, 116);
-- insert into books (author, title, email, priceOld, price) values ('Daron Mathison', 'Streamlined 24/7 website', 'dmathisonb@google.com.au', 522, 110);
-- insert into books (author, title, email, priceOld, price) values ('Amabel Caldera', 'Intuitive well-modulated toolset', 'acalderac@pcworld.com', 231, 109);
-- insert into books (author, title, email, priceOld, price) values ('Roxanne Alday', 'Intuitive context-sensitive service-desk', 'raldayd@imgur.com', 473, 75);
-- insert into books (author, title, email, priceOld, price) values ('Althea Dawidowicz', 'Robust neutral interface', 'adawidowicze@google.co.uk', 582, 108);
-- insert into books (author, title, email, priceOld, price) values ('Nonie Youel', 'Total full-range complexity', 'nyouelf@examiner.com', 416, 146);
-- insert into books (author, title, email, priceOld, price) values ('Lia Crone', 'Enhanced context-sensitive implementation', 'lcroneg@cnbc.com', 231, 147);
-- insert into books (author, title, email, priceOld, price) values ('Kippar Scrowton', 'Universal asynchronous software', 'kscrowtonh@upenn.edu', 282, 58);
-- insert into books (author, title, email, priceOld, price) values ('Marcelline Mollison', 'Balanced bi-directional info-mediaries', 'mmollisoni@tinyurl.com', 222, 129);
-- insert into books (author, title, email, priceOld, price) values ('Johnathan Gerge', 'Object-based full-range intranet', 'jgergej@slate.com', 360, 49);
-- insert into books (author, title, email, priceOld, price) values ('Duff Jirus', 'Phased neutral software', 'djirusk@unc.edu', 546, 53);
-- insert into books (author, title, email, priceOld, price) values ('Bart Vasishchev', 'Synergized uniform array', 'bvasishchevl@samsung.com', 483, 44);
-- insert into books (author, title, email, priceOld, price) values ('Korney Bullus', 'User-friendly web-enabled matrices', 'kbullusm@purevolume.com', 405, 60);
-- insert into books (author, title, email, priceOld, price) values ('Marlee Rycraft', 'Configurable attitude-oriented emulation', 'mrycraftn@naver.com', 456, 81);
-- insert into books (author, title, email, priceOld, price) values ('Harriett Timpany', 'Synergistic optimal collaboration', 'htimpanyo@goo.ne.jp', 554, 76);